version: '3'
services:

  # "microservices"
  # --------------------------------------------------------------------------------------

  giphy-api:
    build: giphy-api/.
    ports:
      - 5574:5574
    volumes:
      - ./giphy-api:/app/
    depends_on:
      - registrator

  news-api:
    build: news-api/.
    ports:
      - 5474:5474
    volumes:
      - ./news-api:/app/
    depends_on:
      - registrator

  search-api:
    build: search-api/.
    ports:
      - 5000:5000
      - 5674:5674
    volumes:
      - ./search-api:/app/
    depends_on:
      - registrator

  search-ui:
    build: search-ui/.
    ports:
      - 8080:80
    volumes:
      - ./search-ui:/var/www/html
    depends_on:
      - registrator

  # "infrastructure" services
  # --------------------------------------------------------------------------------------

  # consul is the service that's responsbile for service discovery
  consul:
    image: gliderlabs/consul-server
    ports:
      - 9500:8500
    command: -bootstrap
    environment:
      SERVICE_8400_IGNORE: 'true'
      SERVICE_8300_IGNORE: 'true'
      SERVICE_8301_IGNORE: 'true'
      SERVICE_8302_IGNORE: 'true'
      SERVICE_8500_IGNORE: 'true'
      SERVICE_8600_IGNORE: 'true'

  # container watcher that registers services in consul
  registrator:
    image: gliderlabs/registrator
    depends_on:
      - consul
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  