version: '3'
services:

  # "microservices"
  # --------------------------------------------------------------------------------------

  search-api:
    build: search-api/.
    ports:
      - 5000:5000
      - 5674:5674
    volumes:
      - ./search-api:/app/

  search-ui:
    build: search-ui/.
    ports:
      - 8080:80
    volumes:
      - ./search-ui:/var/www/html
