version: '2.1'
services:
  giphy-api:
    build: .
    command: npm run debug
    ports:
      - "4000:4000"
      - "5574:5574"
    environment:
      - NODE_ENV=development
      - ENV_ID=dev
      - REGION_NAME=${USER}
      - TSC_NONPOLLING_WATCHER=true
    network_mode: bridge
    volumes:
      - .:/app/
    volumes_from:
      - container:configs-volume:ro
